project_name: goreleaser-demo
before:
  hooks:
    - make clean
    - go mod tidy
env:
  - CGO_ENABLED=0
  - GO11MODULE=on
  - GO111MODULE=on
  - GOPROXY=https://goproxy.io
builds:
  - main: main.go
    binary: goreleaser-demo
    ldflags:
      - -s -w
      - -X main.Version=${{.Version}}
      - -X main.Revision={{.FullCommit}}
      - -X main.BuildUser=goreleaser
      - -X main.BuildDate={{.Date}}
    goos:
      - linux
      - windows
    goarch:
      - amd64
archives:
  - id: archive-package
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - docs/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}_snapshot"
